### PR TITLE
Improve language-meson (pre-0.2.5)

### PR DESCRIPTION
**Pull request by ghost**
This commit includes the following changes:

* Add support for octal and binary literals. (added in 0.47.0)
* Add full support of meson escape sequences. (including octal values, 8-bit hex values, 16-bit hex values, 32-bit hex values, character names in Unicode database)
* Cleanup and improve the grammar file. (removed unused properties from Python grammar, align flow control with other languages, etc.)
* Convert the grammar file to CSON format. (CSON is a strict superset of JSON, let's be standard like other Atom packages)
* Fix broken link in README.md.
* Minor simplification of some regex.
* Refactor test file entirely. (fully reorganized based on Meson's syntax and commented while keeping it simple, it should now match the grammar file and pass every test)
* Remove any reference to floating numbers as Meson supports only integer numbers. (both grammar file and test file now only contains integer numbers)
* Update formatting to be 80 character line length compliant for readability.

### CODE REVIEW

**Comment by ghost** [comment]
Last commit reverted because it broke multiline strings parsing. Everything should be good now.

**Comment by TingPing** [comment]
In the future there is value to smaller commits, like changing the format is independent of other changes.

**Comment by TingPing** [comment]
Also you updated the readme to mention CSON for conversion but that tool doesn't support CSON directly.

**Comment by ghost** [comment]
@TingPing Yeah I should have better split this into multiple commits, I will definitely do it next time.

About the README, instead of mentioning the _CSON file_, how do you think should I rephrase this.

**Comment by ghost** [comment]
@TingPing I updated the README to make it clearer.

**Comment by TingPing** [comment]
@eax0r Thanks :)

**Pull request merged**
